- .github/workflows/build.yml
- Dockerfile
- cmd/main.go
- docs/faq.md
- docs/index.md
- docs/install/linux-service.md
- docs/usage/cli.md
- internal/app/diun.go
- internal/logging/logger.go
- internal/model/cli.go
> Use zoneinfo from Go

- docs/config/index.md
- docs/config/notif.md
- docs/notif/mqtt.md
- go.mod
- go.sum
- internal/model/notif.go
- internal/model/notif_mqtt.go
- internal/notif/client.go
- internal/notif/mqtt/client.go
> Add MQTT notification

- pkg/registry/image.go
- pkg/registry/image_test.go
> Add Hublink for GitHub Container Registry

- docs/user-guides/docker-file-providers.md
- mkdocs.yml
> Add Docker + File providers user guide

- internal/notif/mqtt/client.go
> MQTT Reconnection Log Spam

- internal/app/diun.go
- internal/app/hc.go
- internal/app/job.go
- internal/model/image.go
- internal/model/notif.go
> Handle exclusions as a distinct status

- docs/config/watch.md
- internal/app/diun.go
- internal/model/watch.go
> Make scheduler optional

- pkg/k8s/pod.go
> Avoid duplicated notifications with Kubernetes DaemonSet

- .github/workflows/build.yml
- .github/workflows/docs.yml
- .github/workflows/validate.yml
Follow-up docker/bake-action#8
cc. @justincormack @ccrone @tonistiigi
> Move to docker/bake-action

- internal/app/job.go
Fixes #264 
cc @janekbettinger
> Use digest as comparison footprint

- internal/msg/client.go
- internal/notif/amqp/client.go
- internal/notif/discord/client.go
- internal/notif/gotify/client.go
- internal/notif/mail/client.go
- internal/notif/mail/theme.go
- internal/notif/matrix/client.go
- internal/notif/mqtt/client.go
- internal/notif/pushover/client.go
- internal/notif/rocketchat/client.go
- internal/notif/script/client.go
- internal/notif/slack/client.go
- internal/notif/teams/client.go
- internal/notif/telegram/client.go
- internal/notif/webhook/client.go
Better management and rendering of notification messages. This will allow to set up custom messages as requested in #64 (in further PR).
> Add message client for notifiers

- internal/msg/client.go
> Fix markdown renderer

- internal/notif/pushover/client.go
> Do not check recipient details for Pushover

- docs/usage/cli.md
- internal/logging/logger.go
- internal/model/cli.go
> Allow to disable log color output

- docs/notif/gotify.md
- docs/notif/rocketchat.md
- docs/notif/telegram.md
- internal/model/notif_gotify.go
- internal/model/notif_rocketchat.go
- internal/model/notif_telegram.go
- internal/notif/gotify/client.go
- internal/notif/rocketchat/client.go
- internal/notif/telegram/client.go
> Missing token as secret setting for some notifiers

- docs/notif/telegram.md
- internal/model/notif_telegram.go
- internal/notif/telegram/client.go
> Allow telegram chat IDs as file

- .github/workflows/docs.yml
> Deploy docs on workflow dispatch or tag

- internal/provider/common.go
- internal/provider/docker/container.go
- internal/provider/kubernetes/pod.go
- internal/provider/swarm/service.go
- pkg/docker/image.go
> Handle digest based image reference

- internal/model/cli.go
> Make profiler optional

- Dockerfile
> Remove profiler volume

- .github/CONTRIBUTING.md
- docs/contributing.md
Follow-up https://github.com/crazy-max/diun/pull/345#issuecomment-828697454
> Contribute to doc

- internal/provider/swarm/service.go
> Fix swarm provider

- internal/logging/logger.go
More info https://no-color.org/
> Add `NO_COLOR` support

- docs/faq.md
- docs/install/docker.md
- docs/migration/v3-to-v4.md
- docs/providers/docker.md
- docs/providers/kubernetes.md
- docs/providers/swarm.md
- docs/usage/basic-example.md
- docs/user-guides/docker-file-providers.md
Just in case of strange behaviors like #392
> Define serve command

- go.mod
- internal/app/job.go
- pkg/registry/manifest.go
- pkg/registry/manifest_test.go
- pkg/registry/registry.go
> Avoid notification for unupdated image

- docs/faq.md
- internal/app/job.go
- pkg/registry/registry.go
> Handle registry auth config

- docs/providers/kubernetes.md
> Use arg in kubernetes documentation example

- .github/workflows/build.yml
> Provide mutable tags

- docs/config/index.md
- docs/notif/mail.md
- internal/config/config_test.go
- internal/config/fixtures/config.test.yml
- internal/model/notif_mail.go
- internal/notif/mail/client.go
Fixes #450
cc @romualdvilletet
> Allow multi recipients for email notifier

- docs/faq.md
Closes #220 
cc @Linecutterx @tribal2
> Note to customize the hostname

- internal/model/notif.go
- internal/model/notif_mail.go
- internal/model/notif_rocketchat.go
- internal/model/notif_slack.go
- internal/model/notif_teams.go
- internal/model/notif_telegram.go
> Enhance notif wording

- go.mod
- go.sum
- internal/app/diun.go
Fixes #454 
```
Fri, 20 Aug 2021 22:37:17 CEST INF New image found image=docker.io/crazymax/diun:edge provider=file
Fri, 20 Aug 2021 22:37:20 CEST INF Jobs completed added=2 failed=0 skipped=0 unchanged=0 updated=0
Fri, 20 Aug 2021 22:37:20 CEST INF Cron initialized with schedule 0 */6 * * *
Fri, 20 Aug 2021 22:37:20 CEST INF Next run in 1 hour 22 minutes (2021-08-21 00:00:00 +0200 CEST)
```
cc @oliroe
> Wrong remaining time displayed

- internal/notif/matrix/client.go
> Fix matrix login scheme

- Dockerfile
- cmd/image.go
- docs/usage/command-line.md
- go.mod
- go.sum
- internal/grpc/image.go
- pb/image.pb.go
- pb/image.proto
- pb/image_grpc.pb.go
- test/dockerfile1/mount/Dockerfile1
> Add `image prune` command

- CHANGELOG.md
fixed bad date year in latest release changelog
PS: Welcome to 2022 :D
> Update CHANGELOG.md (Year fix for latest release)

- docs/providers/docker.md
- docs/providers/dockerfile.md
- docs/providers/file.md
- docs/providers/kubernetes.md
- docs/providers/swarm.md
- internal/app/job.go
- internal/model/image.go
- internal/model/job.go
- internal/provider/common.go
- internal/provider/file/file_test.go
- internal/provider/file/fixtures/lscr.yml
follow-up https://github.com/crazy-max/diun/issues/562#issuecomment-1067704789
> Allow customizing the hub link

- docs/usage/command-line.md
> List valid log levels

- .dockerignore
- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/docs.yml
- .github/workflows/e2e.yml
- .github/workflows/labels.yml
- .gitignore
- Dockerfile
- docker-bake.hcl
- hack/gen.Dockerfile
- hack/lint.Dockerfile
- hack/vendor.Dockerfile
> Enhance workflow

- docs/notif/mail.md
- docs/notif/telegram.md
- internal/model/notif_mail.go
- internal/notif/mail/client.go
> Fix email notification message template

- internal/app/hc.go
- internal/msg/client.go
> Fix panics when parsing notification templates

- .github/workflows/e2e.yml
- docs/config/index.md
- docs/config/watch.md
- internal/app/diun.go
- internal/config/config_test.go
- internal/config/fixtures/config.test.yml
- internal/model/watch.go
- test/docker4/diun.yml
> runOnStartup watch option

- internal/provider/nomad/task.go
> Update nomad provider to use mergo

- internal/grpc/image.go
fixes https://github.com/crazy-max/diun/issues/878
> Fix latest for "image list" command

- go.mod
- go.sum
- internal/notif/telegram/client.go
> feat: switch telegram bot library

- Dockerfile
> dockerfile: add tzdata package

- internal/provider/nomad/task.go
> Make sure Nomd TLSConfig struct exists before setting Insecure

- codecov.yml
fix config related to https://docs.codecov.com/docs/github-checks
> chore: update codecov config

- CHANGELOG.md
- docs/migration/v4.1-to-v4.29.md
- docs/notif/telegram.md
- mkdocs.yml
relates to https://github.com/crazy-max/diun/pull/1308#issuecomment-2557342529
> docs: migration notes for telegram notification

- docs/install/docker.md
fixes https://github.com/crazy-max/diun/issues/1256
> docs(#1256): add correction for podman setup

- .github/workflows/build.yml
https://github.com/docker/bake-action/tree/master/subaction/matrix
> ci: use bake matrix subaction
