crazy-max/diun

- doc/install/binary.md
- doc/install/docker.md
- internal/model/cli.go
In order to use the feature introduced in #73 with the docker installation one has to override the [CMD](https://github.com/crazy-max/diun/blob/master/Dockerfile#L63) command from docker-compose applying the flag.
A documented environment variable mapping the flag might be more docker-like. Let me know what you think.
> Add TEST_NOTIF variable for docker installation

- doc/notifications.md
Mattermost explicitly understands slack notifications and works fine with Diun.
> Add Mattermost compatibility via Slack Webhooks

- docs/notif/mqtt.md
- internal/config/config_test.go
- internal/config/fixtures/config.test.yml
- internal/config/fixtures/config.validate.yml
- internal/model/notif_mqtt.go
- internal/notif/mqtt/client.go
With MQTT server behind a reverse proxy, I want to enable TLS connection between diun and MQTT
I tested the four kind of connection manually and it works as expected
The [paho documentation](https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang#ClientOptions.AddBroker) only mention `tcp`/`ssl`/`ws`
But [the library support](https://github.com/eclipse/paho.mqtt.golang/blob/54b5153cb955d512bc82f56455769e61ca3d21e9/netconn.go#L34):
* `ws`
* `wss`
* `mqtt`/`tcp`
* `ssl`/`tls`/`mqtts`/`mqtt+ssl`/`tcps`
* `unix`
Moreover, the only *official* mention of scheme I found, it's [on the mqtt.org wiki](https://github.com/mqtt/mqtt.org/wiki/URI-Scheme#scheme) and seem to prefer `mqtt`/`mqtts` over `tcp`/`ssl`
IMO I prefer `mqtt` over `tcp` since it's less technical and more explicit for the user …
> allow to configure scheme for MQTT broker

- docs/install/docker.md
- docs/install/podman.md
- mkdocs.yml
Running diun on Podman (default container runtime on RHEL, CentOS...) needs a workaround to work, this doc change treats that
> Update docs for Podman support

- pkg/dockerfile/client_test.go
- pkg/dockerfile/fixtures/invalid.Dockerfile
- pkg/dockerfile/fixtures/valid.Dockerfile
- pkg/dockerfile/image.go
- pkg/dockerfile/image_test.go
> Fix Dockerfile parser

- .github/workflows/build.yml
- codecov.yml
- docs/providers/docker.md
- docs/providers/dockerfile.md
- docs/providers/file.md
- docs/providers/kubernetes.md
- docs/providers/swarm.md
- hack/test.Dockerfile
- internal/app/job.go
- internal/model/image.go
- internal/provider/common.go
- internal/provider/file/file_test.go
- internal/provider/file/fixtures/bintray.yml
- internal/provider/file/image.go
Fixes #438
Add `diun.notify_on` to be able to choose status to be notified:
```yaml
services:
redis:
image: redis:latest
labels:
- "diun.enable=true"
- "diun.watch_repo=true"
- "diun.notify_on=new"
restart: always
```
cc @GeoCookie
> Allow to choose status to be notified

- docs/notif/rocketchat.md
It took me quite some time to debug why I don't get notifications in rocketchat.
Finally, I found that the user must have the `bot` role, since the notifications use `alias` propoerties.
See https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/chat-endpoints/postmessage#important for reference.
I added this information to the rocketchat docs.
> Explain roles required for rocketchat notification

- internal/app/job.go
fixes #562
Override hub link using the [`org.opencontainers.image.url` label](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys) if found in the manifest.
> Use OCI image.url label to override hub link

- docs/providers/docker.md
- docs/providers/dockerfile.md
- docs/providers/file.md
- docs/providers/kubernetes.md
- docs/providers/swarm.md
We don't have `numerical` for sort tags type. It should be `semver`
> Fix `sort_tags`

- docs/reporting-issue.md
The repo_url does not contain a trailing slash, so the link is a 404, and with the `q=` query in the URL it searches all Issues & PRs which is not what I think is wanted.
Current URL: https://github.com/crazy-max/diunissues?utf8=%E2%9C%93&q=
New URL: https://github.com/crazy-max/diun/issues?utf8=%E2%9C%93
> Correct the issues URL

- docs/config/index.md
- docs/config/notif.md
- docs/notif/signalrest.md
- internal/model/notif.go
- internal/model/notif_signalrest.go
- internal/notif/client.go
- internal/notif/signalrest/client.go
- mkdocs.yml
Hi,
I created a notification for https://github.com/bbernhard/signal-cli-rest-api 
If you are interested in this notification I can finish the missing things like documentation, enhance code, etc...?
> feat: support signal rest api notifications

- go.mod
- go.sum
follow-up #722 
Use stable release (v1.4.3). cc @IamTheFij
> Bump github.com/hashicorp/nomad/api to f464aca (v1.4.3)

- Dockerfile
Close #744
Changed the file extension from `.tar.tgz` to `.tar.gz`.
> chore: fix the file extension

- docs/install/docker.md
- docs/notif/amqp.md
- docs/notif/discord.md
- docs/notif/gotify.md
- docs/notif/mail.md
- docs/notif/matrix.md
- docs/notif/mqtt.md
- docs/notif/pushover.md
- docs/notif/rocketchat.md
- docs/notif/script.md
- docs/notif/signalrest.md
- docs/notif/slack.md
- docs/notif/teams.md
- docs/notif/telegram.md
- docs/notif/webhook.md
- docs/providers/docker.md
- docs/providers/dockerfile.md
- docs/providers/file.md
- docs/providers/kubernetes.md
- docs/providers/nomad.md
- docs/providers/swarm.md
- docs/usage/command-line.md
- internal/model/notif_signalrest.go
- internal/notif/signalrest/client.go
> Allow customizing Signal notification message

- internal/provider/nomad/task.go
This was intended originally and included in the documentation, but missed in the implementation.
> Check Nomad group meta tags

- docs/config/index.md
- docs/config/notif.md
- docs/notif/ntfy.md
- internal/config/config_test.go
- internal/config/fixtures/config.test.yml
- internal/config/fixtures/config.validate.yml
- internal/model/notif.go
- internal/model/notif_ntfy.go
- internal/notif/client.go
- internal/notif/ntfy/client.go
- mkdocs.yml
Adds notification option for [ntfy.sh](https://ntfy.sh)
fixes #569
> feat(notifications): Adds ntfy.sh notification option

- Dockerfile
- pkg/registry/manifest_test.go
- pkg/registry/tags_test.go
This is one mitigation for #935 and cuts test runtime in half for me.
Note regarding the change to the expected results for the reverse sort: I'm not sure exactly why it was passing before. It's possible that the slice was modified by one of the earlier tests requiring the result to be not quite the proper reversed version. This patch makes sure the slices aren't modified and also fixes the expected result.
> Run slow tests in parallel to improve overall test time

- docs/reporting-issue.md
Also makes the link text more descriptive.
Fixes #962
> Fix dead link in reporting-issue docs

- internal/app/diun.go
- internal/app/job.go
- internal/config/config_test.go
- internal/model/image.go
- internal/model/watch.go
- internal/provider/common.go
- internal/provider/common_test.go
- internal/provider/docker/container.go
- internal/provider/docker/docker.go
- internal/provider/dockerfile/dockerfile.go
- internal/provider/dockerfile/image.go
- internal/provider/file/file.go
- internal/provider/file/file_test.go
- internal/provider/file/image.go
- internal/provider/kubernetes/kubernetes.go
- internal/provider/kubernetes/pod.go
- internal/provider/nomad/nomad.go
- internal/provider/nomad/task.go
- internal/provider/swarm/service.go
- internal/provider/swarm/swarm.go
Allows setting of image configs at a global level to act as default values.
This required a change in the model.Image struct due to a bool field not having a third, unset state. The remedy is to unmarshal into a temporary data structure to detect the presents of a field value and then use that to determine if the default value should be used.
Fixes #491
> Global defaults for image configs

- docs/install/docker.md
… by:
- omit redefining default values
- avoid an artificial container name (mostly not required when using docker compose)
- use the `PWD` env variable instead of spawning a process for the same result
> Follow KISS principle in documentation

- docs/faq.md
- internal/app/job.go
- internal/provider/common.go
- internal/provider/common_test.go
- pkg/registry/manifest.go
- pkg/registry/manifest_test.go
- pkg/registry/ref.go
- pkg/registry/ref_test.go
- test/dockerfile2/mount/Dockerfile
> handle analysis of image with tag and digest

- .github/workflows/e2e.yml
- internal/app/diun.go
- internal/app/job.go
- internal/config/config.go
- internal/config/config_test.go
- internal/config/fixtures/config.test.yml
- internal/model/defaults.go
- internal/model/watch.go
- internal/model/watch_imagedefaults.go
- internal/provider/common.go
- internal/provider/common_test.go
- internal/provider/docker/container.go
- internal/provider/docker/docker.go
- internal/provider/dockerfile/dockerfile.go
- internal/provider/dockerfile/image.go
- internal/provider/file/file.go
- internal/provider/file/file_test.go
- internal/provider/file/image.go
- internal/provider/kubernetes/kubernetes.go
- internal/provider/kubernetes/pod.go
- internal/provider/nomad/nomad.go
- internal/provider/nomad/task.go
- internal/provider/swarm/service.go
- internal/provider/swarm/swarm.go
- test/docker5/diun.yml
related to https://github.com/crazy-max/diun/pull/887
Current implementation of defaults is not working because the `model.Image` struct does not support proper yaml and json tags for the configuration.
Need a dedicated struct for this and also remove some fields that I don't think are necessary. Also move `imageDefaults` from watch to `defaults` in config root.
> fix defaults not handled by yaml configuration

- docs/config/defaults.md
- docs/config/index.md
- docs/config/regopts.md
- docs/config/watch.md
- mkdocs.yml
follow-up #981 
carry and closes #977
@IamTheFij Carry your changes from #977 and refactor after #981 as I have moved imageDefaults from watch to defaults in the configuration.
> Docs for defaults configuration

- pkg/registry/image.go
fixes #970 
We can't directly call pointer receiver methods like `Image.String()` in go `text/template`. Regression introduced by https://github.com/crazy-max/diun/pull/965/commits/bc5cdf7aa11926d6790c4cb386f9cb30e0925fa1.
> fix: do not set Image receiver as pointer

- pkg/registry/manifest_test.go
related to https://github.com/crazy-max/diun/actions/runs/6292267069/job/17081499370#step:4:598
```
#19 111.1 === RUN   TestManifestTaggedDigest
#19 111.1     manifest_test.go:334: 
#19 111.1         	Error Trace:	/src/pkg/registry/manifest_test.go:334
#19 111.1         	Error:      	Not equal: 
#19 111.1         	            	expected: false
#19 111.1         	            	actual  : true
#19 111.1         	Test:       	TestManifestTaggedDigest
#19 111.1     manifest_test.go:338: 
#19 111.1         	Error Trace:	/src/pkg/registry/manifest_test.go:338
#19 111.1         	Error:      	Not equal: 
#19 111.1         	            	expected: "sha256:3fca3dd86c2710586208b0f92d1ec4ce25382f4cad4ae76a2275db8e8bb24031"
#19 111.1         	            	actual  : …
```
> fix non-deterministic test

- docs/notif/pushover.md
- internal/model/notif_pushover.go
- internal/notif/pushover/client.go
Fixes https://github.com/crazy-max/diun/issues/522
Added option to configure notification sound for pushover.
Also updated the documentation to include it and priority as well, because it was undocumented.
> Added sound option for pushover

- pkg/registry/manifest_test.go
- pkg/registry/tags_test.go
Some more tests that take many seconds to run can be made parallel to speed up running. There's a linter for this if you're interested in making this required for tests.
> Parallelize more slow running tests

- internal/notif/ntfy/client.go
fixes https://github.com/crazy-max/diun/issues/1024
Ensure the notification payload includes the "markdown" field set to true.
> Fix NTFY markdown

- Dockerfile
- go.mod
- go.sum
- hack/lint.Dockerfile
- hack/vendor.Dockerfile
When the updated version of Nomad client comes out, I'm planning on a patch to upgrade so that communication over unix socket is available, however the latest requires go 1.21. Rather than bundle a go upgrade with the Nomad change, I thought it best to split up and make sure any potential issues or concerns with the go version are addressed first.
If preferred, I can also close this and instead bundle it with the Nomad upgrade PR.
> Bump Go version up to 1.21

- .golangci.yml
- cmd/image.go
- cmd/notif.go
- hack/lint.Dockerfile
- internal/grpc/image.go
- internal/grpc/notif.go
- internal/notif/mail/client.go
- internal/notif/script/cmd.go
Updates golangci-lint and updates to the correct config format.
Also renames some unused parameters to `_` to appese `revive`.
> Fix linter

- .golangci.yml
"list-mode" does not exist. Also made a change to show all issues.
> chore: fix golangci-lint config

- go.mod
- go.sum
This patch updates the Nomad client to 1.7 bringing the ability to use a Unix Socket to communicate with the Nomad API.
> Enable communication with Nomad using Task API over a unix socket

- internal/provider/file/file_test.go
- internal/provider/file/fixtures/dockerhub.yml
- internal/provider/file/image.go
The `file` provider was not considering the global defaults for `MaxTags`, `IncludeTags`, and `ExcludeTags`.
Updated unit tests to validate they are now considered.
> fix: Use global defaults in File provider

- docs/notif/discord.md
- docs/notif/slack.md
- docs/notif/teams.md
- internal/model/notif_discord.go
- internal/model/notif_slack.go
- internal/model/notif_teams.go
- internal/notif/discord/client.go
- internal/notif/slack/client.go
- internal/notif/teams/client.go
fixes #1228
Adds support as secret for webhook url for discord, slack and teams.
> notif: support webhook url as secret

- docs/notif/telegram.md
- internal/config/config_test.go
- internal/config/fixtures/config.test.yml
- internal/config/fixtures/config.validate.yml
- internal/model/notif_telegram.go
- internal/notif/telegram/client.go
- internal/notif/telegram/client_test.go
fixes https://github.com/crazy-max/diun/issues/948
closes #1125
closes #1305
Carry changes from https://github.com/crazy-max/diun/pull/1125 but merge topics within `chatIDs` with a specific format and add tests.
cc @jon4hz @bytebone
> telegram: add topics support

- internal/notif/gotify/client.go
- internal/notif/ntfy/client.go
- internal/notif/rocketchat/client.go
fixes https://github.com/crazy-max/diun/issues/1007
relates to
* https://github.com/crazy-max/diun/issues/272
* https://github.com/crazy-max/diun/issues/986
> notif: enhance error message for JSON decode response issues

- internal/notif/telegram/client.go
- internal/notif/telegram/client_test.go
relates to https://github.com/crazy-max/diun/pull/1308#issuecomment-2557413995
> telegram: align chatIDs and chatIDsFile format handling

- docs/config/index.md
- docs/config/notif.md
- docs/notif/apprise.md
- internal/config/config_test.go
- internal/config/fixtures/config.test.yml
- internal/model/notif.go
- internal/model/notif_apprise.go
- internal/notif/apprise/client.go
- internal/notif/client.go
- mkdocs.yml
This PR add support to send notification to an apprise api instance. I support both persistent storage (stateful) with the use of the config key and non-persistent storage (stateless) with the of urls. I included the docs for better understanding of the  #solution. Resolve #764
> Apprise notif support

- docs/notif/telegram.md
- internal/config/config_test.go
- internal/model/notif_telegram.go
- internal/notif/telegram/client.go
Close https://github.com/crazy-max/diun/issues/1030.
> Add disable_notification support for telegram.

- docs/faq.md
- docs/notif/apprise.md
- docs/notif/elasticsearch.md
- docs/notif/gotify.md
- docs/notif/ntfy.md
- docs/notif/rocketchat.md
- docs/notif/signalrest.md
- docs/notif/teams.md
- docs/notif/webhook.md
- internal/config/config_test.go
- internal/config/fixtures/config.test.yml
- internal/config/fixtures/config.validate.yml
- internal/model/notif_apprise.go
- internal/model/notif_elasticsearch.go
- internal/model/notif_gotify.go
- internal/model/notif_ntfy.go
- internal/model/notif_rocketchat.go
- internal/model/notif_signalrest.go
- internal/model/notif_teams.go
- internal/model/notif_webhook.go
- internal/notif/apprise/client.go
- internal/notif/elasticsearch/client.go
- internal/notif/gotify/client.go
- internal/notif/ntfy/client.go
- internal/notif/rocketchat/client.go
- internal/notif/signalrest/client.go
- internal/notif/teams/client.go
- internal/notif/webhook/client.go
- pkg/utl/http.go
alternative to, closes #1481
fixes https://github.com/crazy-max/diun/issues/1260
fixes https://github.com/crazy-max/diun/issues/926
Adds `tlsSkipVerify` and `tlsCaCertFiles` for notifiers using HTTP client.
> Add TLS config options for notifiers using HTTP client
